stages:
  generate:
    cmd: python ./uibk/deep_preconditioning/generate_data.py
    deps:
      - ./uibk/deep_preconditioning/generate_data.py
    outs:
      - ./assets/data/raw/sludge_patterns/
    params:
      - number_samples
      - resolution
      - mesh_cells
    desc: Generate linear systems from synthetic sludge patterns.

  train:
    cmd: python ./uibk/deep_preconditioning/train.py
    deps:
      - ./uibk/deep_preconditioning/train.py
      - ./assets/data/raw/sludge_patterns/
    outs:
      - ./assets/checkpoints/
      - ./assets/dvclive/
    params:
      - channels
      - batch_size
      - learning_rate
      - patience
    desc: Train a deep preconditioner on synthetic sludge patterns.

metrics:
  - ./assets/dvclive/metrics.json

params:
  - params.yaml
