stages:
  download:
    cmd: python ./uibk/deep_preconditioning/data_set.py
    outs:
      - ./assets/data/raw/stand-small-problems.zip:
          cache: false
    desc: Download the raw zipped data set from Kaggle
  unzip:
    cmd: unzip ./assets/data/raw/stand-small-problems.zip -d ./assets/data/raw/
    deps:
      - ./assets/data/raw/stand-small-problems.zip
    desc: Unzip the raw data set
