model: PreconditionerNet
data: SludgePatternDataSet
number_samples: 500
resolution: 128
mesh_cells: 2
channels:                             # must be odd due to padding
- 1
- 16
- 32
- 64
- 32
- 16
- 1
batch_size: 4
learning_rate: 0.001
patience: 16
